/*******************************************************************************
 * Software Name : RCS IMS Stack
 *
 * Copyright (C) 2010-2016 Orange.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

package com.gsma.rcs.provider.xms.model;

import com.gsma.services.rcs.RcsService;
import com.gsma.services.rcs.RcsService.Direction;
import com.gsma.services.rcs.cms.XmsMessage;
import com.gsma.services.rcs.contact.ContactId;

public abstract class XmsDataObject {

    /**
     * The message identifier created by the local CMS service.
     */
    private final String mMessageId;
    private final ContactId mContact;
    private final String mMimeType;
    private final Direction mDirection;
    private final long mTimestamp;
    private long mTimestampSent;
    private long mTimestampDelivered;
    private XmsMessage.State mState = XmsMessage.State.QUEUED;
    private XmsMessage.ReasonCode mReasonCode = XmsMessage.ReasonCode.UNSPECIFIED;
    /* package private */RcsService.ReadStatus mReadStatus = RcsService.ReadStatus.UNREAD;
    /**
     * The ID generated by the native SMS application or null if synchronized from CMS
     */
    private final Long mNativeId;
    private final String mChatId;

    public XmsDataObject(String messageId, ContactId contact, String mimeType, Direction dir,
            long timestamp, Long nativeId) {
        mMessageId = messageId;
        mContact = contact;
        mMimeType = mimeType;
        mDirection = dir;
        mTimestamp = timestamp;
        mNativeId = nativeId;
        mChatId = contact.toString();
    }

    public String getMessageId() {
        return mMessageId;
    }

    public ContactId getContact() {
        return mContact;
    }

    public String getMimeType() {
        return mMimeType;
    }

    public Direction getDirection() {
        return mDirection;
    }

    public long getTimestamp() {
        return mTimestamp;
    }

    public void setTimestampSent(long timestampSent) {
        mTimestampSent = timestampSent;
    }

    public long getTimestampSent() {
        return mTimestampSent;
    }

    public void setTimestampDelivered(long timestampDelivered) {
        mTimestampDelivered = timestampDelivered;
    }

    public long getTimestampDelivered() {
        return mTimestampDelivered;
    }

    public XmsMessage.State getState() {
        return mState;
    }

    public void setState(XmsMessage.State state) {
        mState = state;
    }

    public XmsMessage.ReasonCode getReasonCode() {
        return mReasonCode;
    }

    public void setReasonCode(XmsMessage.ReasonCode reasonCode) {
        mReasonCode = reasonCode;
    }

    public Long getNativeId() {
        return mNativeId;
    }

    public RcsService.ReadStatus getReadStatus() {
        return mReadStatus;
    }

    public void setReadStatus(RcsService.ReadStatus readStatus) {
        mReadStatus = readStatus;
    }

    public String getChatId() {
        return mChatId;
    }

    @Override
    public String toString() {
        return "ChatId=" + mChatId + ", MessageId=" + mMessageId + ", Dir=" + mDirection
                + ", Timestamp=" + mTimestamp + ", NativeId=" + mNativeId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof XmsDataObject)) {
            return false;
        }
        XmsDataObject that = (XmsDataObject) o;
        return mMessageId.equals(that.mMessageId) && mContact.equals(that.mContact);
    }

    @Override
    public int hashCode() {
        int result = mMessageId.hashCode();
        result = 31 * result + mContact.hashCode();
        return result;
    }
}
